# Generated by Django 5.2.14 on 2026-05-21 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='channels.channel')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subscribers_total', models.IntegerField(default=0)),
                ('subscribers_gained', models.IntegerField(default=0)),
                ('subscribers_lost', models.IntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('watch_time_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('estimated_revenue_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='channels.channel')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['channel', 'date'], name='analytics_c_channel_b5a6c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'date'), name='uniq_channel_metric_per_day')],
            },
        ),
        migrations.CreateModel(
            name='VideoDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('watch_time_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_view_duration_seconds', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('click_through_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('subscribers_gained', models.IntegerField(default=0)),
                ('subscribers_lost', models.IntegerField(default=0)),
                ('estimated_revenue_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='channels.video')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['video', 'date'], name='analytics_v_video_i_c84fcf_idx')],
                'constraints': [models.UniqueConstraint(fields=('video', 'date'), name='uniq_video_metric_per_day')],
            },
        ),
    ]
