# Generated by Django 5.2.14 on 2026-05-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subscribers_total', models.IntegerField(default=0)),
                ('videos_total', models.IntegerField(default=0)),
                ('views_total', models.BigIntegerField(default=0)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='channels.competitor')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['competitor', 'date'], name='analytics_c_competi_b8ff77_idx')],
                'constraints': [models.UniqueConstraint(fields=('competitor', 'date'), name='uniq_competitor_metric_per_day')],
            },
        ),
    ]
