# Generated by Django 5.2.14 on 2026-05-21 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('planned_publish_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', '下書き'), ('in_review', 'レビュー中'), ('approved', '承認済み'), ('rejected', '差し戻し'), ('published', '公開済み'), ('cancelled', 'キャンセル')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='channels.channel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_plans', to='tenants.tenant')),
            ],
            options={
                'ordering': ['planned_publish_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentPlanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '承認待ち'), ('approved', '承認'), ('rejected', '差し戻し')], default='pending', max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_approvals', to=settings.AUTH_USER_MODEL)),
                ('content_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='content.contentplan')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentPlanComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_comments', to=settings.AUTH_USER_MODEL)),
                ('content_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.contentplan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contentplan',
            index=models.Index(fields=['tenant', 'planned_publish_at'], name='content_con_tenant__3965e1_idx'),
        ),
        migrations.AddIndex(
            model_name='contentplan',
            index=models.Index(fields=['tenant', 'status'], name='content_con_tenant__ca498b_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentplanapproval',
            constraint=models.UniqueConstraint(fields=('content_plan', 'approver'), name='uniq_approver_per_plan'),
        ),
    ]
