# Generated by Django 5.2.14 on 2026-05-21 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('monthly_price_jpy', models.PositiveIntegerField(default=0)),
                ('annual_price_jpy', models.PositiveIntegerField(default=0)),
                ('included_channels', models.PositiveIntegerField(default=1)),
                ('extra_channel_price_jpy', models.PositiveIntegerField(default=0)),
                ('stripe_price_id_monthly', models.CharField(blank=True, max_length=128)),
                ('stripe_price_id_annual', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='trialing', max_length=16)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=128)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=128)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
        ),
    ]
