# Generated by Django 5.2.14 on 2026-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='discord_webhook_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='slack_webhook_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
