# Generated by Django 5.2.14 on 2026-05-21 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_comment_id', models.CharField(blank=True, max_length=64)),
                ('author_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_handled', models.BooleanField(default=False)),
                ('tag', models.CharField(choices=[('untagged', '未分類'), ('good', '好意的'), ('question', '質問'), ('complaint', 'クレーム'), ('spam', 'スパム'), ('other', 'その他')], default='untagged', max_length=16)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tenants.tenant')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='channels.video')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'tag'], name='comments_co_tenant__6fc760_idx'), models.Index(fields=['tenant', 'is_handled'], name='comments_co_tenant__7821dc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('youtube_comment_id', ''), _negated=True), fields=('video', 'youtube_comment_id'), name='uniq_yt_comment_per_video')],
            },
        ),
    ]
