# Generated by Django 5.2.14 on 2026-05-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('comments', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-is_pinned', '-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['tenant', 'is_pinned'], name='comments_co_tenant__2778ec_idx'),
        ),
    ]
