# Generated by Django 5.2.14 on 2026-05-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='channels.competitor'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='source_type',
            field=models.CharField(choices=[('video', '動画一覧（YouTube Studio）'), ('channel', 'チャンネルサマリー'), ('video_daily', '動画 × 日次'), ('channel_daily', 'チャンネル × 日次'), ('competitor_daily', '競合チャンネル × 日次'), ('comments', 'コメント一覧')], max_length=32),
        ),
    ]
